# Generated by Django 3.2.6 on 2021-08-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table='dogs',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='owners',
        ),
    ]
